# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Applied Quantitative Methods
tagline:          'An open course'
description:      'Structure data, build models, and plot results in the R programming language'
url:              dmcglinn.github.io/
baseurl:          /quant_methods

author:
  name:           'Dan McGlinn'
  url:            https://twitter.com/danmcglinn

github:
  repo:           https://github.com/dmcglinn/quant_methods
